### PR TITLE
Add alter_udt_add test

### PR DESCRIPTION
**Pull request by dfaust**
This a test for bug #190 .

Have a look at the line `let my_udt_a = MyUdtA { my_text: "my_text".to_string() };` and change the string to values larger than 8 bytes and watch the index in the panic message change.

### CODE REVIEW

**Comment by AlexPikalov** [comment]
> The command "cargo fmt -- --write-mode=diff" exited with 1.

All tests have passed but I guess I have an old cargo fmt tool, so I would need to fix code formatting.

**Comment by dfaust** [comment]
That's great! Thank you so much. I'll have a look at it tomorrow.

**Comment by dfaust** [comment]
Alright, it works. Both, the test, and my dev database. Thank you.

Regarding rustfmt: It seems the old version `rustfmt` doesn't want to run anymore. So you'll either need the new `rustfmt-nightly` (requires nightly rust) or run `rustfmt` with the `--force` flag.

**Comment by AlexPikalov** [comment]
@dfaust Alright. Will figure it out 👍

**Pull request merged**
