### PR TITLE
cargo fmt is done

### PR DESCRIPTION
**Pull request by harrydevnull**
have run cargo fmt for all the files and has been incorporated into travis as well.
so if we were to push file with a different style travis won't let you build it.

before pushing run
cargo fmt -- --write-mode=diff

if there is anything coming on the console try 
cargo fmt -- --write-mode=overwrite 
cargo test

then push else build would fail

### CODE REVIEW

**Comment by AlexPikalov** [comment]
Let's create  a `.rustfmt.toml` first (#74) so everyone use the same rules. Then we could proceed with reformatting existing code-base.

**Comment by harrydevnull** [comment]
as first cargo clippy I do recommend against that idea.
``` cargo fmt ``` would actually format the src tree and authors are constantly improving fmt plugin. so there is every chance  we that we might have a stale copy of .rustfmt.toml.

generally consensus is not to go for custom rules. [rustfmt](http://johannh.me/blog/rustfmt-ci.html)

**Comment by AlexPikalov** [comment]
Sounds reasonable

**Comment by AlexPikalov** [comment]
BTW do you know, what does it mean that codecov/patch is marked as failed? Coverage was decreased?

**Comment by harrydevnull** [comment]
that seems to be buggy !!! a quick google search showed me some error on codecov side.. yet to dive deep

**Comment by harrydevnull** [comment]
@AlexPikalov can you pls merge this pr ? while I track down what is to be done on codecov/patch

**Comment by AlexPikalov** [comment]
@harrydevnull Yes, I'll merge it. I'm still thinking that the issues is related to coverage degradation.

**Comment by harrydevnull** [comment]
yes and no; 
no coverage didn't go down !
>  related to coverage degradation.
yes it is for some weird reason not all the files have got into to codecov and when we added a new test case that file got tracked and it brought down the coverage for the commit

**Comment by harrydevnull** [comment]
thank you

**Comment by AlexPikalov** [comment]
You're welcome. Great input.

**Pull request merged**
