### PR TITLE
Add native types tests [WIP]

### PR DESCRIPTION
**Pull request by dfaust**
I'm working on improving the integration tests. I'm not done yet, so no need to merge it now. But feedback is appreciated.

I also implemented `Into<Bytes>` for `IpAddr`.

### CODE REVIEW

**Comment by AlexPikalov** [comment]
@dfaust Looks good. Let me know when you are done.

PS May be it makes sense to disable those test execution during appveyor CI as it's done for other integration tests. Then we'd need to fix it in a separate PR.

**Comment by dfaust** [comment]
I think I covered everything of importance from the crud_operations tests now. So merge it if you are happy.
I removed the crud_operations tests since they are obsolete now.
Regarding appveyor, how about adding a new feature and skip integration tests if it's set?

**Comment by dfaust** [comment]
Oh, and I think the create_insert_table tests are pretty much obsolete as well.
I see, they include a tear-down as well. That is very nice of cause. Unfortunately C* is pretty slow when it comes to creating tables and such. So it might not really be desired to tear everything down. But that's up to you.

**Comment by AlexPikalov** [comment]
> Regarding appveyor, how about adding a new feature and skip integration tests if it's set?

Makes sense for me.

**Pull request merged**
