### PR TITLE
CI enabled for windows environment

### PR DESCRIPTION
**Pull request by harrydevnull**
I have enabled the CI for windows env. unit tests are working but the integration tests are still not working as i was unable to get cassandra installed on the windows image

### CODE REVIEW

**Comment by AlexPikalov** [comment]
@harrydevnull Please let me try to check if it works on Windows. What I'm going to do is I'm going to install Windows on a virtual machine inside my OS X. I'll try to connect to Cassandra on OS X out of there.

**Comment by AlexPikalov** [comment]
Wait. Is it possible to run integration tests inside Windows container and to have a second Ubuntu container with Cassandra?

**Comment by harrydevnull** [comment]
Apeveyor is a window based ci engine.
So the source code is compiling and unit test are working.
It is a different container all together .

**Comment by AlexPikalov** [comment]
I see.
Is it possible to make it green? [Build status](https://ci.appveyor.com/project/harrydevnull/cdrs)

**Comment by harrydevnull** [comment]
@AlexPikalov : I have used the wrong badge. now it should work. you might have to login to https://ci.appveyor.com/ and add the project over there. once it is done it would trigger the build.

**Pull request merged**
