### PR TITLE
fix: fix IP parsing error when using hostname

### LINKED ISSUE #322: Cannot use hostname instead of IP-address
Hi there!

Maybe I have been reading the documentation poorly, in that case I apologize. Found similar issues, but they seem to be resolved.

If I run `let node = NodeTcpConfigBuilder::new("192.168.145.139:9042", NoneAuthenticator {}).build();` this will build and work fine. However, if I run:     
`let node = NodeTcpConfigBuilder::new("database:9042", NoneAuthenticator {}).build();` I get this message from the compiler:
`General("invalid IP address syntax")'`. 

Why can't I use hostname?

My toml
```toml
[dependencies]
cdrs = "2.3.0"
```

Cargo --version
`cargo 1.42.0 (86334295e 2020-01-31)`

### PR DESCRIPTION
**Pull request by AlexPikalov**
Fixes #322

### CODE REVIEW

**Comment by nazar-pc** [comment]
@AlexPikalov looks like this wasn't backported to `async-tokio` branch yet

**Comment by AlexPikalov** [comment]
Seems it wasn't

**Comment by nemosupremo** [comment]
Is the workaround to just resolve the DNS manually?

**Comment by nazar-pc** [comment]
Yes, just like this PR does it.

**Pull request merged**
