### PR TITLE
Inserting null causes runtime error

### PR DESCRIPTION
**Pull request by ernestas-poskus**
Noticed that when inserting/reading data that contains NULL causes

> fatal runtime error: out of memory

I reproduced issue below. Couldn't trace error due to lack of details.

cc @AlexPikalov @harrydevnull

### CODE REVIEW

**Comment by harrydevnull** [comment]
@AlexPikalov : this was exactly the reason i was building the `preparedstatement`struct so that we could validate the request even before we reach out to cassandra.

**Comment by harrydevnull** [comment]
@ernestas-poskus  : are you sure it is the insert that is causing the issue?
I just wrote a quick  [test case](https://gist.github.com/harrydevnull/094b0caf350a081a3573c7230d4a2f9b) 
and it seems to be working...

btw the test case which you changed has got a select after that ..
the flow goes this way
```create keyspace --> create tables -->insert values  --> select values --> drop keyspace.```

i did it this way so that the builds are reproducible on travis.
could you please check whether the build is erring on `select value` phase?

**Comment by AlexPikalov** [comment]
@ernestas-poskus for me inserting only a part of fields and then selecting a row works fine.
Any way I'll investigate it and let you know if it's a defect of CDRS itself.

**Comment by AlexPikalov** [comment]
@ernestas-poskus could you please check with latest updates from master? Should work now. I've fixed parsing negative ints and bytes for null and not-set value which have negative lengths.

Thank you for a great catch!

**Comment by ernestas-poskus** [comment]
@AlexPikalov 

Unfortunately not yet but if lets 'map' column type is not binded then it does not crash else it does.

I have rebased on current master and pushed code which makes it happen

**Comment by AlexPikalov** [comment]
@ernestas-poskus I see. I'll take a look for null values once more. Is that correct that null values work fine for 'primitive' types? Because for me it worked yesterday.

As for map/list/set/udt columns with null I'll take a look on those.

As for debugging it's pretty complicated. Maybe it's a primitive way but I'm putting panics to determine on which step we go out of memory. Simple prints don't work - event when I put them before the step where we go out of memory, I don't see any logs. Only playing around with panic helps to figure out where things happen.

**Comment by AlexPikalov** [comment]
And the weird thing is that this error does not provide any stacktrace

**Comment by harrydevnull** [comment]
@AlexPikalov try with `cargo test -- --nocapture`

**Comment by ernestas-poskus** [comment]
> try with cargo test -- --nocapture it might gut out println! s

Thanks but I have an alias `alias ct='cargo test -- --nocapture'` for that 

> And the weird thing is that this error does not provide any stacktrace

indeed

**Comment by AlexPikalov** [comment]
@ernestas-poskus I've pushed a fix which correctly handles null or not-set columns. We have `fn get_by_name(&self, name: &str) -> Option<CDRSResult<R>>;` which internally  gets column type and bytes array and tries to convert bytes into a Rust type basing on that type if following way

1. if column with provided name was not found (in case if table itself does not have such column, or select-request does not contain it) it returns just `None`. Otherwise it returns `Some`

2. if we have `Some` after the first step we can proceed with converting into Rust type. If for conversion it is supposed to have none-empty array of bytes and an actual array of bytes is not empty we're converting into Rust. If an actual bytes array is empty it means that column was not set or is null. In this we're returning `Some(cdrs::Error::General("Column or UDT property is empty".into_string()))`

That's an approach which was implemented

**Pull request merged**
